workflows:
  build-ipa:
    name: Build iOS .ipa
    max_build_duration: 60 # Durata massima della build in minuti
    environment:
      vars:
        FLAVOR: "production"
      node: latest
      xcode: latest
    scripts:
      - name: Installazione dipendenze
        script: |
          npm install --force
      - name: Costruzione del progetto Ionic
        script: |
          ionic build --prod
           npx cap add ios
          npx cap sync ios
      - name: Build IPA
        script: |
          cd ios/App
          pod install
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $HOME/build/App.xcarchive \
            DEVELOPMENT_TEAM="YOUR_TEAM_ID" \
            CODE_SIGN_IDENTITY="Apple Development" \
            archive
          xcodebuild \
            -exportArchive \
            -archivePath $HOME/build/App.xcarchive \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -exportPath $HOME/build/IPA
    artifacts:
      - $HOME/build/IPA/*.ipa
