workflows:
  build-ipa:
    name: Build iOS .ipa
    max_build_duration: 60
    environment:
      groups:
        - ios_bricoscan_signing
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: "$BUNDLE_IDENTIFIER"
      vars:
        FLAVOR: "production"
        APPLE_DEVELOPER_TEAM_ID: "$DEVELOPMENT_TEAM_ID"
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Pulizia del progetto
        script: |
          rm -rf node_modules
          rm -f package-lock.json
          npm cache clean --force

      - name: Installazione dipendenze
        script: |
          npm install --force

      - name: Importazione del certificato .p12 nel keychain
        script: |
          echo "$CERTIFICATE_BASE64" | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain
          security import certificate.p12 -k ~/Library/Keychains/build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "" ~/Library/Keychains/build.keychain

      - name: Importazione del provisioning profile
        script: |
          echo "$PROVISIONING_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/scanapp-provisioning.mobileprovision

      - name: Build Ionic
        script: |
          ionic build --prod

      - name: Aggiunta ios
        script: |
          npx cap add ios
          npx capacitor-assets generate
          npx cap sync ios

      - name: Configurare le impostazioni di firma del codice sul progetto Xcode
        script: |
          xcode-project use-profiles

      - name: Copia exportOptions.plist
        script: |
          cp exportOptions.plist ios/App/

      - name: Build IPA
        script: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates \
            -archivePath $PWD/build/App.xcarchive \
            archive

      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/App.xcarchive \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -exportPath $PWD/build/

      - name: Rimozione del certificato dal keychain
        script: |
          # Rimuove il certificato importato dal keychain
          security delete-certificate -c "iPhone Distribution: Vincenzo Attanasio" ~/Library/Keychains/build.keychain

      - name: Rimozione del certificato .p12
        script: |
          # Rimuove il file .p12 dal filesystem per motivi di sicurezza
          rm -f certificate.p12

    artifacts:
      - $PWD/build/IPA/*.ipa
