workflows:
  build-ipa:
    name: Build iOS .ipa
    max_build_duration: 60
    environment:
      groups:
        - ios_bricoscan_signing
      vars:
        FLAVOR: "production"
        APPLE_DEVELOPER_TEAM_ID: "$DEVELOPMENT_TEAM_ID"
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Pulizia del progetto
        script: |
          rm -rf node_modules
          rm -f package-lock.json
          npm cache clean --force

      - name: Installazione dipendenze
        script: |
          npm install --force

      - name: Build Ionic
        script: |
          ionic build --prod

      - name: Aggiunta ios
        script: |
          npx cap add ios
          npx capacitor-assets generate
          npx cap sync ios

      - name: Decodifica certificato .p12
        script: |
          echo "$CERTIFICATE_BASE64" | base64 --decode > ios/App/certificate.p12

      - name: Decodifica profilo di provisioning
        script: |
          echo "$PROVISIONING_PROFILE_BASE64" | base64 --decode > ios/App/scanapp-provisioning.mobileprovision

      - name: Copia exportOptions.plist
        script: |
          cp exportOptions.plist ios/App/

      - name: Importa certificato
        script: |
          echo "$CERTIFICATE_PASSWORD"
          echo "$CERTIFICATE_BASE64" | base64 --decode > ios/App/certificate.p12
          security import ios/App/certificate.p12 -k ~/Library/Keychains/login.keychain -P KeY1 -T /usr/bin/codesign

      - name: Configura provisioning profile
        script: |
          echo "$PROVISIONING_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/scanapp-provisioning.mobileprovision

      - name: Build IPA
        script: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates \
            -archivePath $PWD/build/App.xcarchive \
            archive

      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/App.xcarchive \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -exportPath $PWD/build/

    artifacts:
      - $PWD/build/IPA/*.ipa
