workflows:
  build-ipa:
    name: Build iOS .ipa
    max_build_duration: 60
    environment:
      groups:
        - ios_bricoscan_signing
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: "com.ionic.scanapp"
      vars:
        FLAVOR: "production"
        APPLE_DEVELOPER_TEAM_ID: "66JC5AYWBZ"
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Pulizia del progetto
        script: |
          rm -rf node_modules
          rm -f package-lock.json
          npm cache clean --force

      - name: Installazione dipendenze
        script: |
          npm install --force

      - name: Build Ionic
        script: |
          ionic build --prod

      - name: Aggiunta ios
        script: |
          npx cap add ios
          sed -i '' 's/platform :ios, '\''13.0'\''/platform :ios, '\''14.0'\''/' ios/App/Podfile
          npx capacitor-assets generate
          npx cap sync ios
          npx cap sync

      - name: Aggiungi permessi camera e gps
        script: |
          /usr/libexec/PlistBuddy -c "Add :NSCameraUsageDescription string 'La fotocamera viene utilizzata per scansionare i codici a barre.'" ios/App/App/Info.plist || \
          /usr/libexec/PlistBuddy -c "Set :NSCameraUsageDescription 'La fotocamera viene utilizzata per scansionare i codici a barre.'" ios/App/App/Info.plist
          /usr/libexec/PlistBuddy -c "Add :NSPhotoLibraryUsageDescription string 'La libreria foto viene utilizzata per accedere alle immagini.'" ios/App/App/Info.plist || \
          /usr/libexec/PlistBuddy -c "Set :NSPhotoLibraryUsageDescription 'La libreria foto viene utilizzata per accedere alle immagini.'" ios/App/App/Info.plist
          /usr/libexec/PlistBuddy -c "Add :NSPhotoLibraryAddUsageDescription string 'La libreria foto viene utilizzata per accedere alle immagini.'" ios/App/App/Info.plist || \
          /usr/libexec/PlistBuddy -c "Set :NSPhotoLibraryAddUsageDescription 'La libreria foto viene utilizzata per accedere alle immagini.'" ios/App/App/Info.plist
          /usr/libexec/PlistBuddy -c "Add :NSLocationWhenInUseUsageDescription string 'Questa app usa la tua posizione per trovare la città.'" ios/App/App/Info.plist || \
          /usr/libexec/PlistBuddy -c "Set :NSLocationWhenInUseUsageDescription 'Questa app usa la tua posizione per trovare la città.'" ios/App/App/Info.plist
          /usr/libexec/PlistBuddy -c "Add :NSLocationAlwaysUsageDescription string 'Questa app usa la tua posizione anche quando è in background.'" ios/App/App/Info.plist || \
          /usr/libexec/PlistBuddy -c "Set :NSLocationAlwaysUsageDescription 'Questa app usa la tua posizione anche quando è in background.'" ios/App/App/Info.plist

      - name: Configurare le impostazioni di firma del codice sul progetto Xcode
        script: |
          xcode-project use-profiles

      - name: Aggiorno la versione dell'app iOS
        script: |
          cd ios
          agvtool new-version -all "1.0.3"

      - name: Copia exportOptions.plist
        script: |
          cp exportOptions.plist ios/App/

      - name: Build IPA
        script: |
          xcodebuild clean
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates \
            -archivePath $PWD/build/App.xcarchive \
            archive

      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/App.xcarchive \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -exportPath $PWD/build/

    artifacts:
      - /Users/builder/clone/build/**/*.ipa
