workflows:
  build-ipa:
    name: Build iOS .ipa
    max_build_duration: 60
    environment:
      groups:
        - ios_bricoscan_signing
      vars:
        FLAVOR: "production"
        APPLE_DEVELOPER_TEAM_ID: "$DEVELOPMENT_TEAM_ID"
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Pulizia del progetto
        script: |
          rm -rf node_modules
          rm -f package-lock.json
          npm cache clean --force

      - name: Installazione dipendenze
        script: |
          npm install --force

      - name: Build Ionic
        script: |
          ionic build --prod

      - name: Aggiunta ios
        script: |
          npx cap add ios
          npx capacitor-assets generate
          npx cap sync ios

      - name: Copia exportOptions.plist
        script: |
          cp exportOptions.plist ios/App/

      - name: Imposta la variabile dell'ID del team
        script: |
          export DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM_ID"

      - name: Firma e crea l'IPA
        script: |
          # Imposta variabili per il certificato e il profilo di provisioning
          export CERT_PATH="$HOME/ci/certificates/scanappcertificate.p12"
          export PROFILE_PATH="$HOME/ci/provisioning/scanapp-provisioning.mobileprovision"

          # Estrai la password dal keychain per il certificato .p12
          security create-keychain -p "" ios-build.keychain
          security import $CERT_PATH -k ios-build.keychain -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign
          security unlock-keychain -p "" ios-build.keychain

          # Imposta il profilo di provisioning
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PROFILE_PATH ~/Library/MobileDevice/Provisioning\ Profiles/

          # Esegui la build
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/App.xcarchive \
            -allowProvisioningUpdates \
            archive

          echo "Contenuto della cartella build:"
            ls -R $PWD/build

          xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/App.xcarchive \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -exportPath $PWD/build/ \
            -allowProvisioningUpdates
    artifacts:
      - $PWD/build/IPA/*.ipa
