workflows:
  build-ipa:
    name: Build iOS .ipa
    max_build_duration: 60
    environment:
      groups:
        - ios_bricoscan_signing
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: "$BUNDLE_IDENTIFIER"
      vars:
        FLAVOR: "production"
        APPLE_DEVELOPER_TEAM_ID: "$DEVELOPMENT_TEAM_ID"
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Pulizia del progetto
        script: |
          rm -rf node_modules
          rm -f package-lock.json
          npm cache clean --force

      - name: Installazione dipendenze
        script: |
          npm install --force

      - name: Build Ionic
        script: |
          ionic build --prod

      - name: Aggiunta ios
        script: |
          npx cap add ios
          npx capacitor-assets generate
          npx cap sync ios

      - name: Configurare le impostazioni di firma del codice sul progetto Xcode
        script: |
          xcode-project use-profiles

      - name: Copia exportOptions.plist
        script: |
          cp exportOptions.plist ios/App/

      - name: Build IPA
        script: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates \
            -archivePath $PWD/build/App.xcarchive \
            CODE_SIGN_IDENTITY="iPhone Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="scanapp-provisioning" \
            archive

      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/App.xcarchive \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -exportPath $PWD/build/

    artifacts:
      - $PWD/build/IPA/*.ipa
