workflows:
  build-ipa:
    name: Build iOS .ipa
    max_build_duration: 60
    environment:
      groups:
        - ios_bricoscan_signing
      vars:
        FLAVOR: "production"
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Pulizia del progetto
        script: |
          rm -rf node_modules
          rm -f package-lock.json
          npm cache clean --force
      - name: Installazione dipendenze
        script: |
          npm install --force
      - name: Build Ionic
        script: |
          ionic build --prod
      - name: Aggiunta ios
        script: |
          npx cap add ios
          npx capacitor-assets generate
          npx cap sync ios
      - name: Configura certificati e provisioning
        script: |
          echo "$CERTIFICATE" | base64 -d > distribution_certificate.p12
          echo "$PROVISIONING_PROFILE" | base64 -d > distribution_profile.mobileprovision
          security import distribution_certificate.p12 -P "$CERTIFICATE_PASSWORD" -A
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp distribution_profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
      - name: Verifica percorso
        script: |
          echo "Current directory: $PWD"
      - name: Firma e crea l'IPA
        script: |
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates \
            -archivePath $PWD/build/App.xcarchive archive
          xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/App.xcarchive \
            -exportOptionsPlist $PWD/ios/exportOptions.plist \
            -exportPath $PWD/build/ \
            -allowProvisioningUpdates
    artifacts:
      - $PWD/build/IPA/*.ipa
